// action types
export const FETCH_SCANNERS_REQUEST = 'FETCH_SCANNERS_REQUEST'
export const FETCH_SCANNERS_SUCCESS = 'FETCH_SCANNERS_SUCCESS'
export const FETCH_SCANNERS_ERROR = 'FETCH_SCANNERS_ERROR'
