// action types
export const FETCH_SCANNERS_REQUEST = 'FETCH_SCANNERS_REQUEST'
export const FETCH_SCANNERS_SUCCESS = 'FETCH_SCANNERS_SUCCESS'
export const FETCH_SCANNERS_ERROR = 'FETCH_SCANNERS_ERROR'
export const FETCH_SCANNER_BY_ID_REQUEST = 'FETCH_SCANNER_BY_ID_REQUEST'
export const FETCH_SCANNER_BY_ID_SUCCESS = 'FETCH_SCANNER_BY_ID_SUCCESS'
export const FETCH_SCANNER_BY_ID_ERROR = 'FETCH_SCANNER_BY_ID_ERROR'
export const CREATE_SCANNER_SUCCESS = 'CREATE_SCANNER_SUCCESS'
export const DELETE_SCANNER_BY_ID_SUCCESS = 'DELETE_SCANNER_BY_ID_SUCCESS'
